---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  releaseName: reloader
  targetNamespace: kube-system
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      version: "1.0.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3

